import { readFileSync } from 'node:fs';
import { escape } from './markup.ts';

type TemplateName = 'document' | 'dialog' | 'figure' | 'entity' | 'entity-context'
  | 'entity-relations' | 'entity-locations' | 'entity-tags' | 'entity-notes';
const templates = new Map<TemplateName, string>();
const readAsset = (name: string) => readFileSync(new URL(`./templates/${name}`, import.meta.url), 'utf8');

export const stylesheet = readAsset('report.css');
export const interactionScript = readAsset('interactions.js');

// Slots are replaced once: ordinary values are escaped, triple braces accept
// HTML generated by our renderers. Templates contain no executable expressions.
export function renderTemplate(name: TemplateName, values: Readonly<Record<string, string>>): string {
  let source = templates.get(name);
  if (source === undefined) {
    source = readAsset(`${name}.html`);
    templates.set(name, source);
  }
  return source.replace(/\{\{\{(\w+)\}\}\}|\{\{(\w+)\}\}/g, (_, raw: string | undefined, text: string | undefined) => {
    const key = (raw ?? text)!;
    if (!Object.hasOwn(values, key)) throw new Error(`Missing template value: ${name}.${key}`);
    return raw ? values[key] : escape(values[key]);
  });
}
